### ISSUE TITLE
restrict to only cloudfront ips

### ISSUE THREAD

**Issue by dagda1** [alphagov/re-paas-ip-safelist-service#3]
We need to whitelist traffic to our GAAP/cloud foundry application to only traffic coming from a cloud foundry distribution.  The reason for this is that we must use a WAF and the WAF will be added to the cloud foundry distribution.

The problem with restricting access to a cloud foundry distribution is that the IPs constantly change.

This [link](https://medium.com/cagataygurturk/restricting-elb-access-to-cloudfront-8b0990dea69f) describes one rather complicated approach.

Is this something you have considered or encountered before?

**Comment by tlwr** [comment]
I'm closing this issue as it is old and no-longer applies to GOV.UK PaaS.

GOV.UK PaaS has static egress IPs, and route services are no longer the only option for adding protective proxies instead of application, we also have internal networking which can be used instead.
